#!/bin/bash

#BUILD_VCS_REF
#BUILD_VERSION
#BUILD_PROJECT_URL
#BUILD_COMMITER_NAME
#BUILD_COMMITER_MAIL


docker build \
  --build-arg BUILD_VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg BUILD_VERSION=`git describe --tags` \
  -t $IMAGE_NAME .